CREATE DATABASE IF NOT EXISTS Userratings;
USE Userratings;
CREATE TABLE IF NOT EXISTS ratings (ID INT NOT NULL PRIMARY KEY, Rating INT, UserID INT, ContentID INT);
CREATE TABLE IF NOT EXISTS content (ID INT NOT NULL PRIMARY KEY, Titel VARCHAR(255), release_date VARCHAR(10) );
CREATE TABLE IF NOT EXISTS our_users (ID INT NOT NULL PRIMARY KEY, Nickname VARCHAR(255), pw_hash VARCHAR(255));

